kind: Pod
apiVersion: v1
metadata:
  name: foo-app
  labels:
    app: foo
spec:
  containers:
    - name: foo-app
      image: hashicorp/http-echo
      args:
        - "-text=foo"
---

kind: Service
apiVersion: v1
metadata:
  name: foo-service
spec:
  selector:
    app: foo
  ports:
    - port: 5678 # Default port for image
---

kind: Pod
apiVersion: v1
metadata:
  name: bar-app
  labels:
    app: bar
spec:
  containers:
    - name: bar-app
      image: hashicorp/http-echo
      args:
        - "-text=bar"
---

kind: Service
apiVersion: v1
metadata:
  name: bar-service
spec:
  selector:
    app: bar
  ports:
    - port: 5678 # Default port for image
# ---
# Simple Path based routing
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: example-ingress
#   annotations:
#     ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /foo
#           backend:
#             serviceName: foo-service
#             servicePort: 5678
#         - path: /bar
#           backend:
#             serviceName: bar-service
#             servicePort: 5678
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
  - host: jenkins.apps.tkgi.lab.khadilkar.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: jenkins
          servicePort: 80
  - host: foo.apps.tkgi.lab.khadilkar.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: foo-service
          servicePort: 5678
  - host: bar.apps.tkgi.lab.khadilkar.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          serviceName: bar-service
          servicePort: 5678
